name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type"
        required: true
        type: choice
        default: auto
        options:
          - auto
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: yarn i

      - name: Validate build
        run: yarn build

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"
          architecture: x64

      - uses: weka/commitizen-action@0.21.0
        with:
          increment: ${{ github.event.inputs.bump != 'auto' && github.event.inputs.bump || '' }}
          commit: false
          push: false
          github_token: ${{ secrets.GHP_TOKEN }}
          extra_requirements: "git+https://github.com/weka/commitizen-version-bump@master"
